### PR TITLE
Pre test, genome_ spawn and mutate updated

### PR DESCRIPTION
**Pull request by leeming**
Code added. Not tested, has dependency on sc_goal tests

### CODE REVIEW

**Comment by ghost** [comment]
See https://github.com/bashrc/scalam/blob/bashrc/next-generation/src/genome.c

**Comment by leeming** [comment]
If you have made improvements, can you push this from your repo then please?

**Comment by ghost** [comment]
See #3

**Comment by leeming** [comment]
superseded by #3

**Pull request closed without merging**
